### Write a function so that the columns of the output matrix are powers of the input vector.

### The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.

In [23]:
import numpy as np

def MyVander(X,N, increasing=False):
    mat = np.empty_like(X)
    X = np.array(X).T
    if (not increasing):
        for i in range(N):
            mat = np.c_[mat, X**(N-i-1)]
        return np.delete(mat, 0, axis=1)
    else:
        for i in range(N):
            mat = np.c_[X**(N-i-1), mat]        
        return np.delete(mat, -1, axis=1)
    
print(MyVander([1,2,3,4,5], 4, False))
print(MyVander([1,2,3,4,5,6], 5, True))


[[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [ 64  16   4   1]
 [125  25   5   1]]
[[   1    1    1    1    1]
 [   1    2    4    8   16]
 [   1    3    9   27   81]
 [   1    4   16   64  256]
 [   1    5   25  125  625]
 [   1    6   36  216 1296]]


### Write a function to find moving average in an array over a window. Test it over `[3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]` and window of 3.

In [54]:
def SMA(X, N):    
    arr = np.zeros(len(X)-N+1)    
    for i in range(len(arr)):
        arr[i] = np.sum(X[i:i+N])/ float(N)      
    print("Length of input array: ", len(X))
    print("Length of moving average array: ",len(arr))  
    return arr
    
SMA(np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]), 3)


Length of input array:  13
Length of moving average array:  11


array([  5.        ,   4.66666667,   5.66666667,   6.66666667,
         9.66666667,  28.66666667,  49.33333333,  72.66666667,
        84.        ,  93.33333333, 116.33333333])